name: Publish image and update manifests
 
on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - ubuntu-latest

      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd
 
jobs:
  ci:
    name: (${{ inputs.environment }}) Push Container image and Update K8s Manifests
    runs-on: "${{ inputs.runner }}"
 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.7
        # uses: ./../../common/actions/checkout-v4.1.7
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 1
          # path: ${{ github.event.repository.name }}-${{ github.ref_name }}
      
      - name: Get image tag
        run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
 
      - name: Configure maven settings.xml
        run: |
          cat <<EOF > ./settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_ADMIN_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
 
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        
      - name: 'ACR login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_LOGIN_SERVER  }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      #- name: Log in to Azure Container Registry
      #  run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ vars.ACR_LOGIN_SERVER  }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      #- name: Log in to Azure Container Registry
      #  run: 
      #    TOKEN=$(az acr login --name ${{ secrets.REGISTRY_USERNAME }} --expose-token --output tsv --query accessToken)
      #    docker login ${{ vars.ACR_LOGIN_SERVER  }} --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< $TOKEN

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        # uses: ./../../common/docker/setup-buildx-action-v3.6.1
 
      - name: Build and push Container image
        uses: docker/build-push-action@v6.5.0
        # uses: ./../../common/docker/build-push-action-v6.5.0
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-cache
          cache-to: type=registry,ref=${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-cache,mode=max
          tags: |
            ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-${{ inputs.environment }}:${{ env.IMAGE_TAG }}
            ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-${{ inputs.environment }}:latest
 
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
        # uses: ./../../common/Azure/setup-kubectl-v4.0.0
        with:
          version: latest
 
      - name: Update kubernetes manifest
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          cd manifests/overlays/${{ inputs.environment }}
          kustomize edit set image ${{ vars.ACR_REPOSITORY }}=${{ vars.ACR_LOGIN_SERVER }}/${{ vars.ACR_REPOSITORY }}-${{ inputs.environment }}:${{ env.IMAGE_TAG }}
 
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '<>' 
          git add .
          git commit -m 'k8s manifest for image tag: ${{ env.IMAGE_TAG }}'
          git push origin main -f
